// created for Configuring Routes
// commented out for lazy loading
// export const About = () => {
// added for lazy loading
const About = () => {
    //commented out for lazy loading
    // return <div>About Page</div>
    // added for lazy loading
    return (
        <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rhoncus ipsum vel libero interdum eleifend. Suspendisse molestie dui vel quam interdum, nec finibus lacus porta. Fusce scelerisque orci nunc, ut sollicitudin ligula aliquet eu. Praesent pellentesque ligula nec lacus eleifend, nec viverra arcu commodo. Duis in ultrices lacus, id egestas leo. Praesent at elit ac arcu luctus eleifend vitae sed elit. Cras vel leo mi.

            Aenean aliquet volutpat diam ultricies porta. In suscipit quam vitae lobortis facilisis. Fusce accumsan ornare velit, ut venenatis lacus rutrum sed. Aliquam erat volutpat. Vivamus accumsan velit ac venenatis sodales. Praesent gravida faucibus lorem id pharetra. Curabitur feugiat varius nunc. Etiam tempus semper est, nec pulvinar lorem commodo volutpat. Mauris a lectus et orci dapibus accumsan. Integer eget ante nec leo interdum faucibus rutrum nec urna. Curabitur posuere ligula eu luctus sodales. Pellentesque tincidunt libero ut mi rutrum consequat. Sed volutpat nunc odio, et eleifend dui iaculis at. Suspendisse dui dolor, tempus id velit sed, tristique convallis eros. Nam eget vestibulum ligula, at tempus orci. Integer lacinia nunc mauris, sit amet posuere nunc commodo et.

            Cras fermentum, odio a ultrices luctus, ligula leo varius dui, ut lobortis lectus nulla in nunc. Nulla lobortis magna a varius sagittis. Nulla accumsan justo at interdum pretium. Nunc ac felis mattis, suscipit eros eu, facilisis nisi. Morbi non libero mauris. Cras congue vel odio ut aliquam. Nunc aliquet ante ac egestas pharetra. Phasellus turpis magna, malesuada et dolor sed, ultricies pulvinar nisl. Curabitur urna magna, consequat vitae efficitur eget, cursus sed elit.

            Morbi vitae erat sapien. Praesent turpis massa, placerat ac vulputate in, pharetra id ligula. Donec aliquet id tortor feugiat pharetra. Donec placerat, ligula et congue lobortis, nisl purus mattis quam, nec commodo nibh arcu sit amet mauris. Nunc quis mattis odio, quis fermentum elit. Curabitur enim diam, tincidunt ac ligula in, aliquet feugiat mauris. In tempor bibendum ullamcorper. Proin elit dui, interdum eget tempor non, tincidunt in nisl. Donec augue purus, interdum a interdum sit amet, ultrices vel risus. Integer vitae eros ac lorem vulputate lobortis. Donec eget tristique risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec interdum justo metus, ullamcorper euismod metus malesuada ut. Aliquam varius mi a dui consequat placerat. Sed aliquam quam vel dui posuere faucibus.

            Pellentesque viverra mi non massa molestie, a convallis nulla vulputate. Donec malesuada at nisl eget varius. Vivamus commodo felis nec ante ornare gravida. Proin consequat aliquam sagittis. Cras eget porttitor massa. Nulla ut ex efficitur, commodo risus sit amet, imperdiet est. Quisque nec ullamcorper sem. Phasellus orci nunc, sollicitudin sed consectetur sit amet, accumsan in metus. Aliquam sollicitudin risus sed lectus pellentesque pharetra. Mauris efficitur justo at imperdiet fringilla.

            Integer ultricies consectetur vulputate. Suspendisse vitae consectetur nunc. Fusce eu sapien eu purus venenatis rhoncus eget a erat. Nulla eu dui nec quam condimentum sodales a et ligula. Cras maximus, quam nec pretium blandit, ante libero tincidunt sapien, nec ultricies turpis justo ut dolor. Maecenas tempor libero vitae dolor vestibulum, a scelerisque magna convallis. Duis risus enim, bibendum vel massa eu, maximus porta erat. Praesent quis ipsum tortor.

            Donec ipsum tellus, dignissim a suscipit rhoncus, dapibus dictum neque. Vestibulum facilisis, felis eget vehicula mattis, magna magna maximus leo, eget congue lectus leo in dui. Phasellus finibus quam auctor aliquet sodales. Donec velit velit, tempus ut diam a, cursus efficitur augue. In leo urna, dapibus a ex at, imperdiet dapibus purus. Cras condimentum eu nunc sit amet auctor. Mauris maximus faucibus leo, id porttitor ligula dignissim at. Morbi vitae rutrum risus. Suspendisse a quam elit. Sed commodo ultrices odio eu semper. Phasellus vel bibendum erat, sit amet porta massa. Integer ac facilisis urna, gravida dapibus nisi. Mauris et sapien vel felis lobortis eleifend vitae vitae sem. Quisque id mauris blandit, dapibus enim lacinia, posuere ligula. Sed tincidunt molestie massa. Donec et lectus lectus.

            In fringilla dignissim magna imperdiet eleifend. Nam eu augue semper, aliquet metus ac, ornare dolor. Nunc lobortis sed lacus ac eleifend. Duis ut tempor diam. Praesent non ligula et massa lobortis dignissim at id sapien. Nullam tempus arcu vel nibh convallis, nec sagittis arcu pulvinar. Integer ac quam nec enim semper tempus eu eget nibh. Donec at leo lectus. Donec vitae viverra lacus, sed sodales massa. Fusce vitae massa elit. Nam id dapibus nunc. Aenean sit amet tincidunt odio.

            Pellentesque sit amet volutpat turpis. Pellentesque mattis mauris at orci porta tincidunt. Vestibulum auctor tortor quis enim facilisis, quis lobortis nulla feugiat. Sed augue metus, sagittis vitae vulputate dignissim, dapibus a nulla. Aenean in velit vel augue elementum porttitor. Ut scelerisque arcu ac consectetur maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse a ipsum et lectus pretium ullamcorper. Duis mauris justo, faucibus at lorem non, aliquam convallis augue. Duis ante metus, placerat at varius vitae, pulvinar ac quam. Fusce maximus justo venenatis, elementum nibh eget, convallis ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin rutrum sed ex et sagittis.

            Etiam faucibus ac est at malesuada. Phasellus et turpis varius, sollicitudin neque vitae, ullamcorper tortor. In vel leo enim. Morbi mauris mi, venenatis luctus lacinia ac, facilisis a risus. Mauris varius vestibulum neque, sed sodales leo pharetra quis. Quisque dolor augue, fermentum nec ornare gravida, pulvinar vitae magna. Nunc mattis et arcu id euismod. Nam cursus lectus vitae sapien sollicitudin, id tincidunt odio ultricies. Curabitur ultrices rhoncus felis. Aliquam vel eros enim. In pulvinar malesuada leo, eu rutrum magna eleifend vitae. Cras posuere nulla non scelerisque ultricies. Vestibulum eu dolor velit. In quam erat, iaculis nec pharetra lacinia, scelerisque id quam. Aenean aliquet nisi eu sapien scelerisque, id commodo arcu malesuada.

            Aliquam varius eu risus vitae tincidunt. In blandit lectus gravida porttitor tristique. Cras convallis vulputate turpis quis sodales. Donec auctor, felis cursus bibendum mattis, nisl lectus mattis dui, eu viverra risus sem et neque. Vivamus pharetra, odio vitae consectetur vehicula, leo lacus gravida felis, dapibus convallis velit justo et augue. Proin arcu ligula, facilisis sed enim sed, auctor sagittis neque. Proin quis augue varius, rutrum felis sit amet, euismod urna. Aenean in eros libero. Morbi tincidunt egestas aliquam. Cras leo risus, bibendum nec sem vitae, tempus ornare tortor. Nulla hendrerit, erat eleifend mattis semper, nisl enim auctor justo, id suscipit nisl tellus in diam. Donec sed nisl vel lectus commodo congue. Phasellus placerat aliquet magna. Suspendisse quis tellus congue, pulvinar nisl a, imperdiet sem. Integer sollicitudin pharetra sapien quis condimentum. Maecenas imperdiet euismod ex, id mollis eros faucibus a.

            Maecenas in orci fermentum, ultricies dolor eu, faucibus dolor. Donec faucibus libero porta orci commodo, sed maximus odio pharetra. Aliquam sed condimentum arcu. Nunc tincidunt justo neque, in eleifend lacus fermentum ac. In in dui quis nisl posuere molestie in et est. Aenean tincidunt ex sit amet diam efficitur sodales. Fusce interdum mattis felis, sit amet auctor purus placerat vel. Fusce a sapien at sem pellentesque mattis in eget eros. Nullam pharetra, dolor id tempus tempus, orci leo vulputate enim, vitae feugiat risus odio vitae mi. Sed augue felis, gravida ut diam quis, ullamcorper rhoncus tellus. Curabitur varius tortor sit amet urna suscipit feugiat. Nam a aliquam ipsum. Quisque tincidunt orci eu felis aliquet, blandit mollis urna posuere. Aenean lectus neque, sollicitudin ullamcorper sem id, suscipit mollis sem. Praesent sagittis massa vitae malesuada interdum.

            Phasellus fermentum condimentum risus in eleifend. Fusce malesuada nunc eu lectus sodales blandit. Phasellus congue felis sem, in ullamcorper mi sodales nec. Duis mattis lectus urna, et luctus sapien volutpat vitae. Ut fermentum placerat velit, nec interdum metus tincidunt eu. Fusce a libero tellus. Fusce egestas risus nec nibh bibendum, sed dictum metus porttitor.

            Phasellus ac pharetra risus. Suspendisse bibendum orci eu consectetur lacinia. Mauris laoreet augue mauris, quis volutpat eros pellentesque sit amet. Aenean in ex blandit, tristique metus eget, venenatis felis. Donec sit amet consectetur sem, vitae posuere turpis. Pellentesque sapien tortor, commodo at orci et, convallis tempor dolor. Suspendisse bibendum posuere elementum. Nulla quis facilisis felis, vitae auctor mauris.

            Aenean semper mi erat, non convallis nisi pharetra quis. Duis sit amet ultricies risus. Nunc dapibus metus mauris. Duis sit amet dictum erat, id ornare magna. Aenean quis enim purus. Sed bibendum tincidunt est, nec molestie enim. Morbi massa nisi, rutrum quis nisl sit amet, tristique feugiat erat. Nam eu ante tellus. Nam pulvinar est sed odio finibus, sed aliquam ante tempor. Ut convallis augue non auctor suscipit. Sed egestas orci id vehicula blandit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam tellus metus, finibus non nibh et, imperdiet consequat est.

            Cras enim sapien, iaculis ac purus eu, ornare hendrerit risus. Maecenas sit amet leo at lectus eleifend dignissim id vitae dui. Curabitur lacinia ornare leo. Donec varius metus nulla. Vestibulum accumsan sollicitudin nibh sit amet pretium. In hac habitasse platea dictumst. Integer non velit eget erat dapibus interdum. Quisque imperdiet consequat sem. Nulla et aliquam orci. Aliquam metus turpis, luctus nec orci vitae, congue varius turpis. Pellentesque et congue neque, non egestas sapien. Nullam fermentum fringilla sodales. Pellentesque vel est facilisis, aliquam est eu, laoreet mi. Curabitur maximus mi velit, a aliquam neque hendrerit elementum. Mauris quis sapien porta, iaculis nisi ut, varius lorem.

            Cras tincidunt eget mauris eu vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eget hendrerit urna, id condimentum lacus. Nam nisl dui, accumsan sed condimentum et, ultrices non libero. Etiam tortor magna, malesuada sed odio rutrum, malesuada finibus dui. Donec vulputate neque eget turpis pharetra, et rutrum eros hendrerit. Fusce maximus risus eget lorem fringilla, et lobortis neque vulputate. Fusce mi felis, sodales a tortor vitae, blandit feugiat sapien.

            Vivamus ac dapibus felis. Maecenas molestie, erat id rutrum euismod, urna risus dapibus erat, in ultricies nunc lacus ac diam. Vivamus eu tortor vitae nisi accumsan pulvinar. Aenean laoreet viverra purus, eget consectetur felis feugiat et. Pellentesque nisl nisi, interdum id nunc ac, dapibus consectetur massa. Suspendisse felis nunc, mollis sed nisl eu, volutpat egestas eros. Aenean eu maximus mauris. Praesent at gravida quam. Aenean ornare tempor ex, id aliquet nisi pulvinar ut. In at neque dolor. Pellentesque semper urna interdum, congue nibh quis, congue purus. Vestibulum malesuada ornare dolor, ac eleifend arcu condimentum id. Ut gravida, dui a rhoncus sagittis, enim dui cursus quam, ac eleifend velit lacus a dui. Suspendisse sem dui, ultricies in tellus eu, bibendum auctor magna. Maecenas congue vel massa et sagittis.

            Cras vestibulum quam non augue sagittis, sed molestie ligula egestas. Proin auctor vestibulum diam, ac pharetra neque dignissim id. Donec nulla orci, semper vitae malesuada vel, lacinia ut lectus. Quisque pulvinar interdum faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas tincidunt nulla id mauris consequat, ac egestas odio hendrerit. Sed posuere, arcu quis laoreet blandit, nulla justo semper mi, eget commodo tellus arcu eu massa. Morbi id lacus ut ligula hendrerit efficitur eget vel elit. Pellentesque nec convallis massa. Vivamus ut dolor tempor, pulvinar leo at, commodo justo. Curabitur non aliquam elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla eget purus molestie, sagittis lorem sit amet, condimentum dui.

            Mauris sit amet leo at ipsum varius euismod ut nec arcu. Morbi rhoncus accumsan rutrum. Pellentesque convallis tellus sem, sed pulvinar lorem dignissim rhoncus. Mauris tempor odio a ligula egestas, at convallis mauris fringilla. Suspendisse scelerisque euismod nisl, quis dapibus urna ullamcorper et. Phasellus feugiat ante ut congue vehicula. Donec sed dignissim risus, ac consequat tortor. Quisque tristique mauris quis mattis accumsan. Nulla lobortis, eros quis lacinia posuere, augue ipsum porta neque, in pellentesque mauris diam at tortor. Integer nisi dui, sollicitudin dictum lorem porttitor, auctor dapibus nisi. Aliquam in nibh vitae nulla bibendum consectetur. Nullam tempor dignissim mi, quis vulputate erat ultrices non. Duis vulputate leo non suscipit lobortis.
        </div>
    )
}

// added for lazy loading
export default About